// server/players.ts
import { Player } from './types';

export const playerDatabase: Player[] = [
  {
    id: 'p1',
    name: 'Virat Kohli',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316600/316605.3.png',
    role: 'Batsman',
    country: 'India',
    basePrice: 2.0,
    rating: 95,
    battingRating: 97,
    bowlingRating: 15,
  },
  {
    id: 'p2',
    name: 'Rohit Sharma',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316600/316601.3.png',
    role: 'Batsman',
    country: 'India',
    basePrice: 2.0,
    rating: 93,
    battingRating: 95,
    bowlingRating: 10,
  },
  {
    id: 'p3',
    name: 'Jasprit Bumrah',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316537.3.png',
    role: 'Bowler',
    country: 'India',
    basePrice: 2.0,
    rating: 96,
    battingRating: 10,
    bowlingRating: 98,
  },
  {
    id: 'p4',
    name: 'MS Dhoni',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316533.3.png',
    role: 'Wicket-Keeper',
    country: 'India',
    basePrice: 2.0,
    rating: 90,
    battingRating: 88,
    bowlingRating: 5,
  },
  {
    id: 'p5',
    name: 'Ravindra Jadeja',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316527.3.png',
    role: 'All-Rounder',
    country: 'India',
    basePrice: 2.0,
    rating: 92,
    battingRating: 82,
    bowlingRating: 88,
  },
  {
    id: 'p6',
    name: 'KL Rahul',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316519.3.png',
    role: 'Wicket-Keeper',
    country: 'India',
    basePrice: 2.0,
    rating: 88,
    battingRating: 90,
    bowlingRating: 5,
  },
  {
    id: 'p7',
    name: 'Hardik Pandya',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316515.3.png',
    role: 'All-Rounder',
    country: 'India',
    basePrice: 2.0,
    rating: 87,
    battingRating: 80,
    bowlingRating: 75,
  },
  {
    id: 'p8',
    name: 'Rishabh Pant',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316523.3.png',
    role: 'Wicket-Keeper',
    country: 'India',
    basePrice: 2.0,
    rating: 86,
    battingRating: 85,
    bowlingRating: 5,
  },
  {
    id: 'p9',
    name: 'Suryakumar Yadav',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316535.3.png',
    role: 'Batsman',
    country: 'India',
    basePrice: 2.0,
    rating: 89,
    battingRating: 92,
    bowlingRating: 10,
  },
  {
    id: 'p10',
    name: 'Shubman Gill',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316521.3.png',
    role: 'Batsman',
    country: 'India',
    basePrice: 2.0,
    rating: 85,
    battingRating: 88,
    bowlingRating: 8,
  },
  {
    id: 'p11',
    name: 'Yuzvendra Chahal',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316509.3.png',
    role: 'Bowler',
    country: 'India',
    basePrice: 2.0,
    rating: 84,
    battingRating: 10,
    bowlingRating: 90,
  },
  {
    id: 'p12',
    name: 'Mohammed Shami',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316541.3.png',
    role: 'Bowler',
    country: 'India',
    basePrice: 2.0,
    rating: 86,
    battingRating: 12,
    bowlingRating: 91,
  },
  {
    id: 'p13',
    name: 'Pat Cummins',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316400/316487.3.png',
    role: 'Bowler',
    country: 'Australia',
    basePrice: 2.0,
    rating: 91,
    battingRating: 40,
    bowlingRating: 93,
  },
  {
    id: 'p14',
    name: 'Mitchell Starc',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316400/316491.3.png',
    role: 'Bowler',
    country: 'Australia',
    basePrice: 2.0,
    rating: 89,
    battingRating: 25,
    bowlingRating: 94,
  },
  {
    id: 'p15',
    name: 'David Warner',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316400/316493.3.png',
    role: 'Batsman',
    country: 'Australia',
    basePrice: 2.0,
    rating: 88,
    battingRating: 92,
    bowlingRating: 10,
  },
  {
    id: 'p16',
    name: 'Glenn Maxwell',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316400/316483.3.png',
    role: 'All-Rounder',
    country: 'Australia',
    basePrice: 2.0,
    rating: 85,
    battingRating: 84,
    bowlingRating: 60,
  },
  {
    id: 'p17',
    name: 'Travis Head',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316400/316479.3.png',
    role: 'Batsman',
    country: 'Australia',
    basePrice: 1.5,
    rating: 84,
    battingRating: 86,
    bowlingRating: 25,
  },
  {
    id: 'p18',
    name: 'Jos Buttler',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316300/316395.3.png',
    role: 'Wicket-Keeper',
    country: 'England',
    basePrice: 2.0,
    rating: 88,
    battingRating: 90,
    bowlingRating: 5,
  },
  {
    id: 'p19',
    name: 'Ben Stokes',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316300/316399.3.png',
    role: 'All-Rounder',
    country: 'England',
    basePrice: 2.0,
    rating: 90,
    battingRating: 85,
    bowlingRating: 78,
  },
  {
    id: 'p20',
    name: 'Jofra Archer',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316300/316389.3.png',
    role: 'Bowler',
    country: 'England',
    basePrice: 2.0,
    rating: 85,
    battingRating: 20,
    bowlingRating: 90,
  },
  {
    id: 'p21',
    name: 'Rashid Khan',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316200/316223.3.png',
    role: 'Bowler',
    country: 'Afghanistan',
    basePrice: 2.0,
    rating: 90,
    battingRating: 45,
    bowlingRating: 94,
  },
  {
    id: 'p22',
    name: 'Kane Williamson',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316200/316233.3.png',
    role: 'Batsman',
    country: 'New Zealand',
    basePrice: 2.0,
    rating: 87,
    battingRating: 90,
    bowlingRating: 20,
  },
  {
    id: 'p23',
    name: 'Trent Boult',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316200/316217.3.png',
    role: 'Bowler',
    country: 'New Zealand',
    basePrice: 2.0,
    rating: 86,
    battingRating: 15,
    bowlingRating: 91,
  },
  {
    id: 'p24',
    name: 'Quinton de Kock',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316200/316255.3.png',
    role: 'Wicket-Keeper',
    country: 'South Africa',
    basePrice: 1.5,
    rating: 85,
    battingRating: 87,
    bowlingRating: 5,
  },
  {
    id: 'p25',
    name: 'Kagiso Rabada',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316200/316259.3.png',
    role: 'Bowler',
    country: 'South Africa',
    basePrice: 2.0,
    rating: 88,
    battingRating: 15,
    bowlingRating: 92,
  },
  {
    id: 'p26',
    name: 'AB de Villiers',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316200/316251.3.png',
    role: 'Batsman',
    country: 'South Africa',
    basePrice: 2.0,
    rating: 94,
    battingRating: 96,
    bowlingRating: 20,
  },
  {
    id: 'p27',
    name: 'Babar Azam',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316100/316185.3.png',
    role: 'Batsman',
    country: 'Pakistan',
    basePrice: 2.0,
    rating: 90,
    battingRating: 93,
    bowlingRating: 10,
  },
  {
    id: 'p28',
    name: 'Shaheen Afridi',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316100/316189.3.png',
    role: 'Bowler',
    country: 'Pakistan',
    basePrice: 2.0,
    rating: 87,
    battingRating: 15,
    bowlingRating: 91,
  },
  {
    id: 'p29',
    name: 'Yashasvi Jaiswal',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316543.3.png',
    role: 'Batsman',
    country: 'India',
    basePrice: 1.5,
    rating: 84,
    battingRating: 86,
    bowlingRating: 15,
  },
  {
    id: 'p30',
    name: 'Kuldeep Yadav',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316517.3.png',
    role: 'Bowler',
    country: 'India',
    basePrice: 1.5,
    rating: 83,
    battingRating: 15,
    bowlingRating: 87,
  },
  {
    id: 'p31',
    name: 'Shreyas Iyer',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316529.3.png',
    role: 'Batsman',
    country: 'India',
    basePrice: 2.0,
    rating: 83,
    battingRating: 85,
    bowlingRating: 10,
  },
  {
    id: 'p32',
    name: 'Ishan Kishan',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316513.3.png',
    role: 'Wicket-Keeper',
    country: 'India',
    basePrice: 1.5,
    rating: 80,
    battingRating: 82,
    bowlingRating: 5,
  },
  {
    id: 'p33',
    name: 'Sanju Samson',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316525.3.png',
    role: 'Wicket-Keeper',
    country: 'India',
    basePrice: 1.5,
    rating: 82,
    battingRating: 84,
    bowlingRating: 5,
  },
  {
    id: 'p34',
    name: 'R Ashwin',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316505.3.png',
    role: 'Bowler',
    country: 'India',
    basePrice: 2.0,
    rating: 87,
    battingRating: 50,
    bowlingRating: 92,
  },
  {
    id: 'p35',
    name: 'Axar Patel',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316507.3.png',
    role: 'All-Rounder',
    country: 'India',
    basePrice: 1.5,
    rating: 81,
    battingRating: 70,
    bowlingRating: 80,
  },
  {
    id: 'p36',
    name: 'Devdutt Padikkal',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316511.3.png',
    role: 'Batsman',
    country: 'India',
    basePrice: 1.0,
    rating: 76,
    battingRating: 78,
    bowlingRating: 10,
  },
  {
    id: 'p37',
    name: 'Washington Sundar',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316545.3.png',
    role: 'All-Rounder',
    country: 'India',
    basePrice: 1.0,
    rating: 78,
    battingRating: 65,
    bowlingRating: 75,
  },
  {
    id: 'p38',
    name: 'Mohammed Siraj',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316539.3.png',
    role: 'Bowler',
    country: 'India',
    basePrice: 1.5,
    rating: 82,
    battingRating: 10,
    bowlingRating: 86,
  },
  {
    id: 'p39',
    name: 'Marcus Stoinis',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316400/316489.3.png',
    role: 'All-Rounder',
    country: 'Australia',
    basePrice: 1.5,
    rating: 80,
    battingRating: 78,
    bowlingRating: 65,
  },
  {
    id: 'p40',
    name: 'Faf du Plessis',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316200/316253.3.png',
    role: 'Batsman',
    country: 'South Africa',
    basePrice: 1.5,
    rating: 83,
    battingRating: 86,
    bowlingRating: 10,
  },
  {
    id: 'p41',
    name: 'Heinrich Klaasen',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316200/316257.3.png',
    role: 'Wicket-Keeper',
    country: 'South Africa',
    basePrice: 1.5,
    rating: 82,
    battingRating: 85,
    bowlingRating: 5,
  },
  {
    id: 'p42',
    name: 'Liam Livingstone',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316300/316393.3.png',
    role: 'All-Rounder',
    country: 'England',
    basePrice: 1.5,
    rating: 80,
    battingRating: 82,
    bowlingRating: 55,
  },
  {
    id: 'p43',
    name: 'Sam Curran',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316300/316397.3.png',
    role: 'All-Rounder',
    country: 'England',
    basePrice: 2.0,
    rating: 82,
    battingRating: 70,
    bowlingRating: 78,
  },
  {
    id: 'p44',
    name: 'Rachin Ravindra',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316200/316229.3.png',
    role: 'All-Rounder',
    country: 'New Zealand',
    basePrice: 1.0,
    rating: 78,
    battingRating: 80,
    bowlingRating: 60,
  },
  {
    id: 'p45',
    name: 'Bhuvneshwar Kumar',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316503.3.png',
    role: 'Bowler',
    country: 'India',
    basePrice: 1.0,
    rating: 79,
    battingRating: 30,
    bowlingRating: 84,
  },
  {
    id: 'p46',
    name: 'Deepak Chahar',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316501.3.png',
    role: 'Bowler',
    country: 'India',
    basePrice: 1.0,
    rating: 77,
    battingRating: 40,
    bowlingRating: 82,
  },
  {
    id: 'p47',
    name: 'Ruturaj Gaikwad',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316531.3.png',
    role: 'Batsman',
    country: 'India',
    basePrice: 1.0,
    rating: 80,
    battingRating: 83,
    bowlingRating: 10,
  },
  {
    id: 'p48',
    name: 'Prithvi Shaw',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316547.3.png',
    role: 'Batsman',
    country: 'India',
    basePrice: 0.75,
    rating: 74,
    battingRating: 78,
    bowlingRating: 5,
  },
  {
    id: 'p49',
    name: 'Arshdeep Singh',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316549.3.png',
    role: 'Bowler',
    country: 'India',
    basePrice: 1.0,
    rating: 79,
    battingRating: 10,
    bowlingRating: 83,
  },
  {
    id: 'p50',
    name: 'Tilak Varma',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316551.3.png',
    role: 'Batsman',
    country: 'India',
    basePrice: 0.5,
    rating: 76,
    battingRating: 79,
    bowlingRating: 30,
  },
  {
    id: 'p51',
    name: 'Nicholas Pooran',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316100/316147.3.png',
    role: 'Wicket-Keeper',
    country: 'West Indies',
    basePrice: 1.5,
    rating: 81,
    battingRating: 84,
    bowlingRating: 5,
  },
  {
    id: 'p52',
    name: 'Andre Russell',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316100/316149.3.png',
    role: 'All-Rounder',
    country: 'West Indies',
    basePrice: 2.0,
    rating: 86,
    battingRating: 85,
    bowlingRating: 72,
  },
  {
    id: 'p53',
    name: 'Sunil Narine',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316100/316155.3.png',
    role: 'All-Rounder',
    country: 'West Indies',
    basePrice: 2.0,
    rating: 85,
    battingRating: 75,
    bowlingRating: 88,
  },
  {
    id: 'p54',
    name: 'Shimron Hetmyer',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316100/316151.3.png',
    role: 'Batsman',
    country: 'West Indies',
    basePrice: 1.0,
    rating: 77,
    battingRating: 80,
    bowlingRating: 10,
  },
  {
    id: 'p55',
    name: 'Phil Salt',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316300/316391.3.png',
    role: 'Wicket-Keeper',
    country: 'England',
    basePrice: 1.5,
    rating: 80,
    battingRating: 83,
    bowlingRating: 5,
  },
  {
    id: 'p56',
    name: 'Mark Wood',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316300/316401.3.png',
    role: 'Bowler',
    country: 'England',
    basePrice: 1.5,
    rating: 82,
    battingRating: 15,
    bowlingRating: 88,
  },
  {
    id: 'p57',
    name: 'Venkatesh Iyer',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316553.3.png',
    role: 'All-Rounder',
    country: 'India',
    basePrice: 0.75,
    rating: 74,
    battingRating: 76,
    bowlingRating: 55,
  },
  {
    id: 'p58',
    name: 'Rahul Tripathi',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316555.3.png',
    role: 'Batsman',
    country: 'India',
    basePrice: 0.75,
    rating: 75,
    battingRating: 79,
    bowlingRating: 10,
  },
  {
    id: 'p59',
    name: 'Umran Malik',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316500/316557.3.png',
    role: 'Bowler',
    country: 'India',
    basePrice: 0.5,
    rating: 73,
    battingRating: 10,
    bowlingRating: 80,
  },
  {
    id: 'p60',
    name: 'Devon Conway',
    photo: 'https://img1.hscicdn.com/image/upload/f_auto,t_h_100/lsci/db/PICTURES/CMS/316200/316219.3.png',
    role: 'Batsman',
    country: 'New Zealand',
    basePrice: 1.0,
    rating: 80,
    battingRating: 84,
    bowlingRating: 10,
  },
];
